name: mocktail_image_network
description: A Dart package which allows you to mock Image.network in your widget tests with confidence using the mocktail package.
version: 0.0.1-dev.1
repository: https://github.com/felangel/mocktail
homepage: https://github.com/felangel/mocktail/packages/mocktail_image_network

environment:
  sdk: ">=2.12-0-0 <3.0.0"

dependencies:
  mocktail: ^0.0.1-dev.11

dev_dependencies:
  coverage: ^0.14.2
  test: ">=1.16.0-nullsafety.13 <1.16.0"
