version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "packages/mocktail"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "packages/mocktail/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "packages/mocktail_image_network"
    schedule:
      interval: "daily"