name: example
description: An example of mocktail usage
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  mocktail:
    path: ../
  test: ^1.16.0
  custom_lint: ^0.2.0
  mocktail_lints:
    path: ../../mocktail_lints

analyzer:
  plugins:
    - custom_lint
