name: mocktail
description: A Dart mocking library which simplifies mocking with null safety support and no manual mocks or code generation.
version: 0.0.1-dev.11
repository: https://github.com/felangel/mocktail
homepage: https://github.com/felangel/mocktail

environment:
  sdk: ">=2.12-0-0 <3.0.0"

dependencies:
  matcher: ^0.12.10

dev_dependencies:
  coverage: ^0.14.2
  test: ^1.16.0
