name: example
description: An example of mocktail_image_network usage
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: 1.25.0-8.3.pre

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail_image_network:
    path: ../
