name: mocktail

on:
  push:
    paths:
      - "packages/mocktail/**"
      - ".github/workflows/mocktail.yaml"

  pull_request:
    paths:
      - "packages/mocktail/**"
      - ".github/workflows/mocktail.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/mocktail
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12-dev
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test example
      - name: Run Tests
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
          FLUTTER_PUB_CACHE: ${{env.FLUTTER_HOME}}/.pub-cache/bin
        run: |
          flutter pub global activate coverage
          export PATH=$PATH:$FLUTTER_DART_HOME
          export PATH=$PATH:$FLUTTER_PUB_CACHE
          dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/mocktail/coverage/lcov.info
